apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp-deployment
  namespace: default
  labels:
    app: k8sapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sapp-deployment
  # serviceName: "k8sapp-deployment"      
  template:
    metadata:
      labels:
        app: k8sapp-deployment
    spec:
      # volumes:
      #   - name: vol-test
      #     persistentVolumeClaim:
      #       claimName: my-pvc
          # hostPath:
          #   path: /data/logs
            
      containers:
        - name: k8sapp-deployment
          image: IMAGE_TAG
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          command: ["service nginx start"]
          # volumeMounts:
          #   - mountPath: usr/share/nginx/html
          #     name: vol-test

---

apiVersion: v1
kind: Service
metadata:
  name: k8sapp-deployment
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: k8sapp-deployment


              

     
                         
    
