apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp-deployment
  namespace: default
  labels:
    app: k8sapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sapp-deployment
  template:
    metadata:
      labels:
        app: k8sapp-deployment
    spec:
      # volumes:
      #   - name: vol-test
      #     persistentVolumeClaim:
      #       claimName: my-pvc
          # hostPath:
          #   path: /data/logs
            
      containers:
        - name: k8sapp-deployment
          image: omar2023/lara101:1424b5c6ac7cc133f7376c036b21f1858ed99506-nginx-worker
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          # command: ["echo","nginx ----v"]
          # volumeMounts:
          #   - mountPath: usr/share/nginx/html
          #     name: vol-test
              

     
                         
      

---
apiVersion: v1
kind: Service
metadata:
  name: k8sapp-internal-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: k8sapp-deployment
