version: "3"
services:
    app:
      build:
       context: .
       dockerfile: Dockerfile
      container_name: job101
      image: omar2023/job101:155-job101-pipline  
      ports:
       - "82:80"

