version: "3.2"
services:
    app:
      build:
       context: .
       dockerfile: Dockerfile
      container_name: job101
      image: dockerImage 
      ports:
       - "82:80"
      volumes:
        - job101-vol:/agent
volumes:
  job101-vol:
     driver: local        

