apiVersion: v1
kind: Service
metadata:
  name: k8sapp-lb-service
spec:
  selector:
    app: k8sapp-deployment
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31510     